export enum CommandType {

    PLAY = "PLAY",

    PAUSE = "PAUSE",

    NEXT = "NEXT",

    PREVIOUS = "PREVIOUS",

    VOLUME = "VOLUME",

    SEEK = "SEEK",

    MUTE = "MUTE",

    UNMUTE = "UNMUTE",

    STOP = "STOP",

    OPEN_VIDEO = "OPEN_VIDEO",

    FULLSCREEN = "FULLSCREEN",

    EXIT_FULLSCREEN = "EXIT_FULLSCREEN",

    TOGGLE_FULLSCREEN = "TOGGLE_FULLSCREEN",

    ADD_PLAYLIST = "ADD_PLAYLIST",

    REMOVE_PLAYLIST = "REMOVE_PLAYLIST",

    CLEAR_PLAYLIST = "CLEAR_PLAYLIST",

    PLAY_PLAYLIST_ITEM = "PLAY_PLAYLIST_ITEM",

    SHUFFLE_PLAYLIST = "SHUFFLE_PLAYLIST",

    REPEAT_OFF = "REPEAT_OFF",

    REPEAT_ONE = "REPEAT_ONE",

    REPEAT_ALL = "REPEAT_ALL",

    SKIP_AD = "SKIP_AD"
}