export enum CommandType {

    PLAY = "PLAY",

    PAUSE = "PAUSE",

    NEXT = "NEXT",

    PREVIOUS = "PREVIOUS",

    VOLUME = "VOLUME",

    SEEK = "SEEK",

    MUTE = "MUTE",

    UNMUTE = "UNMUTE",

    STOP = "STOP",

    OPEN_VIDEO = "OPEN_VIDEO",

    FULLSCREEN = "FULLSCREEN",

    EXIT_FULLSCREEN = "EXIT_FULLSCREEN",

    TOGGLE_FULLSCREEN = "TOGGLE_FULLSCREEN",

    ADD_QUEUE = "ADD_QUEUE",

    REMOVE_QUEUE = "REMOVE_QUEUE",

    CLEAR_QUEUE = "CLEAR_QUEUE",
}